---
name: build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  ci:
    name: >
      Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    container:
      image: erlang:${{matrix.otp_vsn}}
    strategy:
      matrix:
        otp_vsn: [22.0, 22.1, 22.2, 22.3,
                  23.0, 23.1, 23.2,
                  23.3.4.4, 23.3, # point after which we no longer need `partial_chain`
                  24.0.3, 24.0]   # point after which we no longer need `partial_chain`
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: apt update && apt install sudo
      - run: RUNNING_ON_CI=true make check test
