---
name: Tests and Checks
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  ci:
    name: >
      Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: ['23.1']
        os: ['windows-2019']
        rebar3_vsn: ['3.18', '3.20']
        exclude:
          # rebar 3.20
          - rebar3_vsn: '3.20'
            otp_vsn: '22.0'
          - rebar3_vsn: '3.20'
            otp_vsn: '22.1'
          - rebar3_vsn: '3.20'
            otp_vsn: '22.2'
          - rebar3_vsn: '3.20'
            otp_vsn: '22.3'

          # rebar 3.18
          - rebar3_vsn: '3.18'
            otp_vsn: '23.0'
          - rebar3_vsn: '3.18'
            otp_vsn: '23.1'
          - rebar3_vsn: '3.18'
            otp_vsn: '23.2'
          - rebar3_vsn: '3.18'
            otp_vsn: '23.3'
          #
          - rebar3_vsn: '3.18'
            otp_vsn: '24.0'
          - rebar3_vsn: '3.18'
            otp_vsn: '24.1'
          - rebar3_vsn: '3.18'
            otp_vsn: '24.2'
          - rebar3_vsn: '3.18'
            otp_vsn: '24.3'
          #
          - rebar3_vsn: '3.18'
            otp_vsn: '25.0'
          - rebar3_vsn: '3.18'
            otp_vsn: '25.1'
          - rebar3_vsn: '3.18'
            otp_vsn: '25.2'
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: ${{matrix.rebar3_vsn}}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: restore _build
        uses: actions/cache@v3
        with:
          path: _build
          key: _build-cache-for-os-${{runner.os}}-otp-${{matrix.otp_vsn}}-rebar3-${{matrix.rebar3_vsn}}-hash-${{hashFiles('rebar.lock')}}
      - name: restore rebar3's cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/rebar3
          key: rebar3-cache-for-os-${{runner.os}}-otp-${{matrix.otp_vsn}}-rebar3-${{matrix.rebar3_vsn}}-hash-${{hashFiles('rebar.lock')}}
      - run: make check test
