---
name: Tests and Checks
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  ci:
    name: >
      Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: ['25.3']
        # otp_vsn: ['22.0', '22.1', '22.2', '22.3',
        #           '23.0', '23.1', '23.2', '23.3',
        #           '24.0', '24.1', '24.2', '24.3',
        #           '25.0', '25.1', '25.2', '25.3']
        os: ['ubuntu-20.04', 'windows-2019']
        rebar3_vsn: ['3.18', '3.20']
        exclude:
          # rebar 3.20
          - rebar3_vsn: '3.20'
            otp_vsn: '22.0'
          - rebar3_vsn: '3.20'
            otp_vsn: '22.1'
          - rebar3_vsn: '3.20'
            otp_vsn: '22.2'
          - rebar3_vsn: '3.20'
            otp_vsn: '22.3'

          # rebar 3.18
          - rebar3_vsn: '3.18'
            otp_vsn: '23.0'
          - rebar3_vsn: '3.18'
            otp_vsn: '23.1'
          - rebar3_vsn: '3.18'
            otp_vsn: '23.2'
          - rebar3_vsn: '3.18'
            otp_vsn: '23.3'
          #
          - rebar3_vsn: '3.18'
            otp_vsn: '24.0'
          - rebar3_vsn: '3.18'
            otp_vsn: '24.1'
          - rebar3_vsn: '3.18'
            otp_vsn: '24.2'
          - rebar3_vsn: '3.18'
            otp_vsn: '24.3'
          #
          - rebar3_vsn: '3.18'
            otp_vsn: '25.0'
          - rebar3_vsn: '3.18'
            otp_vsn: '25.1'
          - rebar3_vsn: '3.18'
            otp_vsn: '25.2'
          - rebar3_vsn: '3.18'
            otp_vsn: '25.3'
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: ${{matrix.rebar3_vsn}}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Non-Windows: set dynamic env (1)
        if: ! startsWith(${{runner.os}}, 'windows-')
        run: |
          echo "prev_github_run_number=$((${{github.run_number}} - 1))" >> "$GITHUB_ENV"
          echo "build_cache_prefix=_build-cache-for-os-${{runner.os}}-otp-${{matrix.otp_vsn}}-rebar3-${{matrix.rebar3_vsn}}" >> "$GITHUB_ENV"

      - name: Non-Windows: set dynamic env (2)
        if: ! startsWith(${{runner.os}}, 'windows-')
        run: |
          echo "build_cache_prefix_with_hash=${{env.build_cache_prefix}}-hash-${{hashFiles('rebar.lock')}}" >> "$GITHUB_ENV"

      - name: Windows: set dynamic env (1)
        if: startsWith(${{runner.os}}, 'windows-')
        run: |
          # https://github.com/actions/runner-images/issues/5251#issuecomment-1071030822
          echo "prev_github_run_number=$(${{github.run_number}} - 1)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "build_cache_prefix=_build-cache-for-os-${{runner.os}}-otp-${{matrix.otp_vsn}}-rebar3-${{matrix.rebar3_vsn}}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Windows: set dynamic env (2)
        if: startsWith(${{runner.os}}, 'windows-')
        run: |
          echo "build_cache_prefix_with_hash=${{env.build_cache_prefix}}-hash-${{hashFiles('rebar.lock')}}" >> "$GITHUB_ENV" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: restore cached build artifacts
        uses: actions/cache/restore@v3
        with:
          path: _build
          key: ${{env.build_cache_prefix_with_hash}}-${{env.prev_github_run_number}}
          restore-keys:
            ${{env.build_cache_prefix_with_hash}}-
            ${{env.build_cache_prefix}}-

      - run: make check test

      - name: save build artifacts
        uses: actions/cache/save@v3
        with:
          path: _build
          key: ${{env.build_cache_prefix_with_hash}}-${{github.run_number}}
